title: Learning GitHub Pages
author: Erin B
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I created this site while going through the tutorial to learn
  GitHub Pages to create a new site.
  This description will appear in the document head meta (for
  Google search results) and in the feed.xml site description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
